function [Kp,Kd,Ki] = CourseAutoP(wb,zeta)
%CourseAutoP
%    [Kp,Kd,Ki] = CourseAutoP(WB,ZETA)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Jun-2022 18:36:38

t2 = zeta.^2;
t6 = sqrt(2.0);
t3 = t2.^2;
t4 = t2.*2.0;
t5 = t3.*2.0;
t7 = -t4;
t8 = t5+t7+1.0;
t9 = sqrt(t8);
t10 = t6.*t9;
t11 = t7+t10+1.0;
Kp = (wb.^2.*5.927187073888691e+11)./t11;
if nargout > 1
    Kd = 1.0./sqrt(t11).*wb.*zeta.*1.185437414777738e+12-2.822470035185091e+10;
end
if nargout > 2
    Ki = 1.0./t11.^(3.0./2.0).*wb.^3.*5.92718707388869e+10;
end
