function [KpY,KdY,KiY] = TUG_SwayPIDGains(wbY,zetaY)
%TUG_SwayPIDGains
%    [KpY,KdY,KiY] = TUG_SwayPIDGains(wbY,zetaY)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Jun-2022 18:36:45

t2 = zetaY.^2;
t3 = t2.^2;
t4 = t2.*2.0;
t5 = t2.*4.0;
t6 = t3.*4.0;
t7 = -t4;
t8 = -t5;
t9 = t6+t8+2.0;
t10 = sqrt(t9);
t11 = t7+t10+1.0;
KpY = (wbY.^2.*1.180858028364e+6)./t11;
if nargout > 1
    KdY = 1.0./sqrt(t11).*wbY.*zetaY.*2.361716056728e+6-1.476072535455e+4;
end
if nargout > 2
    KiY = 1.0./t11.^(3.0./2.0).*wbY.^3.*1.180858028364e+5;
end
