function [Msurge,Kp,Ki] = TUG_SurgePI(wbX,zetaX)
%TUG_SurgePI
%    [Msurge,Kp,Ki] = TUG_SurgePI(wbX,zetaX)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    06-Jun-2022 18:36:45

Msurge = 8.708580283640001e+5;
if nargout > 1
    t2 = zetaX.^2;
    t3 = t2.^2;
    t4 = t2.*2.0;
    t5 = t2.*4.0;
    t6 = t3.*4.0;
    t7 = -t4;
    t8 = -t5;
    t9 = t6+t8+2.0;
    t10 = sqrt(t9);
    t11 = t7+t10+1.0;
    Kp = 1.0./sqrt(t11).*wbX.*zetaX.*1.741716056728e+6-1.741716056728e+4;
end
if nargout > 2
    Ki = (wbX.^2.*8.708580283640001e+5)./t11;
end
